# Generated by Django 6.0.6 on 2026-06-12 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Record',
            fields=[
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('method', models.CharField(default='Unknown', max_length=100)),
                ('note', models.TextField(blank=True)),
                ('receipt_url', models.URLField(blank=True, max_length=500)),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Request',
            fields=[
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('type', models.CharField(choices=[('loan', 'Loan'), ('investment', 'Investment'), ('contribution', 'Contribution')], max_length=50)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('title', models.CharField(blank=True, max_length=255)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('pending_secretary', 'Pending Secretary'), ('pending_audit', 'Pending Audit'), ('proposed', 'Proposed'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=50)),
                ('receipt_url', models.URLField(blank=True, max_length=500)),
                ('votes', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('decided_at', models.DateTimeField(blank=True, null=True)),
                ('decided_by', models.CharField(blank=True, max_length=255)),
            ],
        ),
    ]
