# Generated by Django 6.0.6 on 2026-07-16 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finances', '0004_alter_record_options_alter_request_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loan',
            name='status',
            field=models.CharField(choices=[('pending_secretary', 'Pending Secretary'), ('pending_treasury', 'Pending Treasury'), ('pending_audit', 'Pending Audit'), ('pending_chair', 'Pending Chair'), ('pending_signature', 'Pending Signature'), ('pending_disbursal', 'Pending Disbursal'), ('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('repaid', 'Repaid')], default='pending_secretary', max_length=30),
        ),
        migrations.AlterField(
            model_name='request',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('pending_secretary', 'Pending Secretary'), ('pending_treasury', 'Pending Treasury'), ('pending_audit', 'Pending Audit'), ('pending_chair', 'Pending Chair'), ('proposed', 'Proposed'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('active', 'Active')], default='pending', max_length=50),
        ),
    ]
